POST https://my-greet-api.onrender.com/api/greet
content-type: application/json

{
	"language" : "xhosa",
	"greeting" : "Molo"
}

### 

POST https://my-greet-api.onrender.com/api/greet
content-type: application/json

{
	"language" : "zulu",
	"greeting" : "Sawubona"
}

